### ISSUE TITLE
laskutus.inc eräpäivän laskenta ei toimi, korjaus

### ISSUE THREAD

**Issue by akirjavainen** [devlab-oy/pupesoft#2773]
Pieni bugiraportti. Jouduin muuttamaan laskutus.inc -tiedostosta PHP:n operaattoreita, koska eräpäivän laskenta ei muuten toiminut. Aika ei riitä virittelemään pull requestia tähän hätään, mutta tässä pikaisesti, mistä ongelmassa oli kyse. PHP-versiona oli tällä koneella käytössä vanhempi 5.3.3.1.

Rivi 1004:
EI TOIMI: $xrow['abs_pvm'] === null
KORJAUS: $xrow['abs_pvm'] == '0000-00-00'

Rivi 1012:
EI TOIMI: $xrow['abs_pvm'] !== null
KORJAUS: $xrow['abs_pvm'] != '0000-00-00'

Rivi 1019:
EI TOIMI: $xrow['kassa_abspvm'] !== null
KORJAUS: $xrow['kassa_abspvm'] != '0000-00-00'

Rivi 1020:
EI TOIMI: $xrow['kassa_abspvm'] === null
KORJAUS: $xrow['kassa_abspvm'] == '0000-00-00'

**Comment by juppe** [comment]
Kiitos ilmoituksestasi @akirjavainen ! Sanoisin, että ongelmasi johtuu maksuehto-taulun rakenteesta. Varmista, että  maksuehto-taulussa "abs_pvm"- ja "kassa_abspvm"-kenttien rakenne on allaolevan mukainen:
```SQL
+--------------------+--------------+------+-----+---------+-------+
| Field              | Type         | Null | Key | Default | Extra |
+--------------------+--------------+------+-----+---------+-------+
| abs_pvm            | date         | YES  |     | NULL    |       |
| kassa_abspvm       | date         | YES  |     | NULL    |       |
+--------------------+--------------+------+-----+---------+-------+
```

Seuraavat updatet voisi varmasti myös olla paikallaan:

```SQL
UPDATE maksuehto SET kassa_abspvm = null WHERE kassa_abspvm = '0000-00-00';
UPDATE maksuehto SET abs_pvm = null WHERE abs_pvm = '0000-00-00';
```

Tämän jälkeen homman pitäisi toimia.
